[[redirects]]
  from = "/1080p"
  to = "/"
  status = 200

[[redirects]]
  from = "/upload"
  to = "/"
  status = 200

[[redirects]]
  from = "/_480_720"
  to = "/"
  status = 200

[[redirects]]
  from = "/_576_864"
  to = "/"
  status = 200

[[redirects]]
  from = "/_768_1152"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960"
  to = "/"
  status = 200