[[redirects]]
  from = "/uploadAkbank"
  to = "/"
  status = 200

[[redirects]]
  from = "/uploadAkmerkez_Akbank"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920_Sabit"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1920_1080_Sabit"
  to = "/"
  status = 200

[[redirects]]
  from = "/_384_960_Cekim"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1344_416_Cekim"
  to = "/"
  status = 200

[[redirects]]
  from = "/_2160_3840_Cekim"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920_Cekim"
  to = "/"
  status = 200

[[redirects]]
  from = "/_960_2016_Cekim"
  to = "/"
  status = 200

[[redirects]]
  from = "/_384_960_Akbank"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1344_416_Akbank"
  to = "/"
  status = 200

[[redirects]]
  from = "/_2160_3840_Akbank"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920_Akbank"
  to = "/"
  status = 200

[[redirects]]
  from = "/_960_2016_Akbank"
  to = "/"
  status = 200

[[redirects]]
  from = "/_2160_3840_Switch_Akbank"
  to = "/"
  status = 200

[[redirects]]
  from = "/1080p"
  to = "/"
  status = 200

[[redirects]]
  from = "/upload"
  to = "/"
  status = 200

[[redirects]]
  from = "/uploadBagdat"
  to = "/"
  status = 200

[[redirects]]
  from = "/uploadKanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/uploadZorlu"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920_Kanyon_Switch"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920_Bagdat_Switch"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920_Zorlu_Giris"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920_Zorlu"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1440_1080_Zorlu"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1920_1080_Zorlu"
  to = "/"
  status = 200

[[redirects]]
  from = "/_864_720_Kanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1920_1152_Kanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1152_704_Kanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1280_704_Kanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1548_946_Kanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/_512_786_Kanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920_Kanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1024_460_Kanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1024_640_Kanyon"
  to = "/"
  status = 200

[[redirects]]
  from = "/_2160_3840_Bagdat"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920_Stand"
  to = "/"
  status = 200

[[redirects]]
  from = "/_icon_led"
  to = "/"
  status = 200

[[redirects]]
  from = "/_384_960"
  to = "/"
  status = 200

[[redirects]]
  from = "/_480_720"
  to = "/"
  status = 200

[[redirects]]
  from = "/_512_786"
  to = "/"
  status = 200

[[redirects]]
  from = "/_576_336"
  to = "/"
  status = 200

[[redirects]]
  from = "/_576_864"
  to = "/"
  status = 200

[[redirects]]
  from = "/_624_1040"
  to = "/"
  status = 200

[[redirects]]
  from = "/_640_1120"
  to = "/"
  status = 200

[[redirects]]
  from = "/_640_1140"
  to = "/"
  status = 200

[[redirects]]
  from = "/_648_384"
  to = "/"
  status = 200

[[redirects]]
  from = "/_720_480"
  to = "/"
  status = 200

[[redirects]]
  from = "/_768_1152"
  to = "/"
  status = 200

[[redirects]]
  from = "/_768_1344"
  to = "/"
  status = 200

[[redirects]]
  from = "/_864_432"
  to = "/"
  status = 200

[[redirects]]
  from = "/_864_576"
  to = "/"
  status = 200

[[redirects]]
  from = "/_864_720"
  to = "/"
  status = 200

[[redirects]]
  from = "/_864_1440"
  to = "/"
  status = 200

[[redirects]]
  from = "/_960_640"
  to = "/"
  status = 200

[[redirects]]
  from = "/_960_2016"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1024_640"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_600"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1080_1920"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1088_576"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1152_640"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1152_704"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1152_720"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1152_768"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1280_704"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1280_800"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1440_1080"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1536_960"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1548_946"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1920_1080"
  to = "/"
  status = 200

[[redirects]]
  from = "/_1920_1152"
  to = "/"
  status = 200

[[redirects]]
  from = "/_2160_3840"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960_v1"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960_v2"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960_v3"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960_v4"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960_v5"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960_v6"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960_v7"
  to = "/"
  status = 200

[[redirects]]
  from = "/_4092_960_v8"
  to = "/"
  status = 200


